name: fsm2
version: 0.17.3
homepage: https://github.com/bsutton/fsm2
description: FSM2 provides an implementation of the core design aspects of the UML state diagrams allowing both declarative transitions and dynamic transitions along with Guard Conditions.
environment: 
  sdk: '>=2.10.0 <3.0.0'
dependencies: 
  args: ^1.6.0
  completer_ex: ^1.0.0
  dcli: ^0.41.0
  meta: ^1.2.0
  path: ^1.7.0
  stacktrace_impl: ^1.0.0
  synchronized: ^2.2.0+2
  tree_iterator: ^1.0.1
dev_dependencies: 
  
  lint: ^1.0.0
  mockito: ^4.1.1
  test: 1.16.0-nullsafety.7
executables: 
  fsm2: 
