name: fsm2
version: 0.9.2
homepage: https://github.com/bsutton/fsm2
description: FSM2 provides an implementation of the core design aspects of the UML state diagrams allowing both declarative transitions and dynamic transitions along with Guard Conditions.
environment: 
  sdk: '>=2.9.0 <3.0.0'
dependencies: 
  synchronized: ^2.2.0+2
  meta: ^1.1.8
dev_dependencies: 
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
  dcli: ^0.34.0
