name: fsm
description: A library for finite State machine realization in Dart. Inspired by Tinder StateMachine for Kotlin.
version: 0.0.5
homepage: https://github.com/ookami-kb/fsm

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:

dev_dependencies:
  build_runner: ^1.7.4
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
